
name: Secret manager
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: jpoehnelt/secrets-sync-action@v1.7.0
        with:
          SECRETS: |
            ^FOO$
            ^CONTAINER*
          REPOSITORIES: |
            Josh-01/test-app-workflow
          DRY_RUN: true                   # Update this to false to create the secrets
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          CONCURRENCY: 10
        env:
         FOO: ${{secrets.FOO1}} # Will be picked up
         FOOBAR: BAZ # will not be picked up
